services:
  laravel-web-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ADMIN_EMAIL=${ADMIN_EMAIL:-test@example.com}
        - ADMIN_PASSWORD=${ADMIN_PASSWORD:-password}
    ports:
      - "8000:8000"
